### ISSUE TITLE
Tabs inside Drawer component doesn't work correctly on v40.0.0

### ISSUE THREAD

**Issue by loeliarigault** [Sage/carbon#3214]
### Current behaviour
After update carbon version to 40.0.0.
Tabs inside Drawer component doesn't work correctly :
we got the error _setTarget is not a function when we call handleChange.
We don't have this problem in the version 39.2.1
You can test that in the sandbox  https://codesandbox.io/s/busy-chebyshev-fkbnc?file=/src/index.js.

### Expected behaviour
Tabs inside Drawer component has no regression : no "_setTarget  error" raised.

### Reproducible example
https://codesandbox.io/s/busy-chebyshev-fkbnc?file=/src/index.js
Use this sandbox and change carbon version : 
v39.2.1 : ok
v40.0.0 : ko

### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| carbon-react     | 40.0.0
| React            | 16.13.1
| Browser          | Chrome
| npm              | 6.14.2
| Operating System | Windows

**Comment by jamime** [comment]
It looks like this prop should be optional, until we fix this you can use the following workaround
```js
<Drawer sidebar={tabs()} setTarget={() => {}} />
```
caused by
https://github.com/Sage/carbon/blob/7fe79d3d9ae9039a2ed34d1cb075df2bcc455d7d/src/components/drawer/__internal__/drawer.component.js#L164

**Comment by jamime** [comment]
FE-3143
